### ISSUE TITLE
Error: During launch of Corefig! ReturnCode:1 Windows server core 2016

### ISSUE THREAD

**Issue by ecomstation** [ejsiron/Corefig#1]
Hi all,

i've installed .net  4 and .net 2 frameworks, but i still get the error 

Windows server core 2016 ita

any help?
thanks

massimo

**Comment by ejsiron** [comment]
Try to bypass the wsf and run CoreFig.ps1 directly.

**Comment by ejsiron** [comment]
Unable to reproduce and no response to suggestion, closing.
