### ISSUE TITLE
windows, buttons and policy size

### ISSUE THREAD

**Issue by knut1er** [ejsiron/Corefig#2]
Hello,
I think it is due to the high resolution on rdp client computers, but the text inside objects is too large. I can not see entire text. In the Windows Update window, I can not see the validation button.
Can we resize windows?
Thanks for your great job!

**Comment by ejsiron** [comment]
I created a new branch named "resizable". As time permits I will update each dialog to be resizable.
For now, I have committed a new Updates.ps1 that makes it resizable. Please try that out and let me know if it meets your needs. If it does, I will work through the other dialogs as I can.

**Comment by knut1er** [comment]
Thank you for your check.
Ok it works, you can see "Apply" or other buttons.
You can see the result [here ](https://lanexplore-my.sharepoint.com/:i:/g/personal/jlch_lan-explore_fr/Ef7xYMtRR2ROjjVcyaJKHIkBFV5rotYijinMwiZ-DE0Rtg?e=ujKosC) on my RDP Session.

**Comment by ejsiron** [comment]
Merged into primary branch, will add to ISO/ZIP at a later date
